CREATE TABLE Account (
    AccountId INT PRIMARY KEY IDENTITY(1,1),
    AccountGuid UNIQUEIDENTIFIER NOT NULL,
    Username NVARCHAR(100) NOT NULL,
    Password NVARCHAR(100) NOT NULL,
    Role NVARCHAR(20) NOT NULL,
    Status NVARCHAR(1) NOT NULL DEFAULT 'A'
);
CREATE TABLE Member (
    MemberId INT PRIMARY KEY IDENTITY(1,1),
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    Gender NVARCHAR(10) NOT NULL,
    Age INT NOT NULL,
    MembershipType NVARCHAR(50) NOT NULL,
    AccountId INT NOT NULL UNIQUE,
    FOREIGN KEY (AccountId) REFERENCES Account(AccountId)
);
CREATE TABLE Trainer (
    TrainerId INT PRIMARY KEY IDENTITY(1,1),
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    Specialization NVARCHAR(100) NOT NULL,
    AccountId INT NOT NULL UNIQUE,
    FOREIGN KEY (AccountId) REFERENCES Account(AccountId)
);
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Account';
